import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "안녕하세요 about page 입니다",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <Link href={"/contact"}>contact</Link>
    </div>
  );
};

export default AboutPage;
